version: '3.7'
services:
    postgres:
        container_name: postgres-fastapi
        image: postgres
        hostname: postgres-fastapi
        restart: always
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
          - '5432:5432'
        volumes:
          - postgres-data:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin-fastapi
      image: dpage/pgadmin4
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "5050:80"
volumes:
  postgres-data: